// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlH60rScZuXD1JkhQY-se2fQDF8MONWO0',
    appId: '1:142046286826:web:3c317f50847fcb0babd893',
    messagingSenderId: '142046286826',
    projectId: 'fasum-7ade0',
    authDomain: 'fasum-7ade0.firebaseapp.com',
    storageBucket: 'fasum-7ade0.firebasestorage.app',
    measurementId: 'G-M683EGP62D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7sfnWbQJt5OBjQ3JMamHaYkCNh2Dv1Vc',
    appId: '1:142046286826:android:55ef677287bf12d7abd893',
    messagingSenderId: '142046286826',
    projectId: 'fasum-7ade0',
    storageBucket: 'fasum-7ade0.firebasestorage.app',
  );
}
