// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsgL9KMWjsUTB_Y8lcsWS7mUlFrpWw5hk',
    appId: '1:154089128944:web:c91112bb43cd2a5581d335',
    messagingSenderId: '154089128944',
    projectId: 'first-app-17b61',
    authDomain: 'first-app-17b61.firebaseapp.com',
    databaseURL: 'https://first-app-17b61-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-17b61.firebasestorage.app',
    measurementId: 'G-2GHF1D2XHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdGcz_0DYHDZ1S7MLpWzdRVdkHZ_ZXBRM',
    appId: '1:154089128944:android:dd1df687944a1f6481d335',
    messagingSenderId: '154089128944',
    projectId: 'first-app-17b61',
    databaseURL: 'https://first-app-17b61-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-17b61.firebasestorage.app',
  );

}